# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
tagline:          'Entrepreneur public'
baseurl:          /
paginate:         500
collections:      episodes:
  output:         true

# Podcast parameters
podcast_title:    Hackers publics
podcast_description:  À la rencontre de ceux qui transforment la culture numérique de l'administration

#SEO tag
title:            Frédéric Bardolle
description:      Innovation publique, éthique & IA
url:              https://f14e.fr
author:
  name:           'Frédéric Bardolle'
  twitter:        seiteta
social:
  name:           Frédéric Bardolle
  links:
                  - https://twitter.com/seiteta
                  - https://www.linkedin.com/in/fbardolle
lang:             fr

plugins:
                  - jekyll-seo-tag
