# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
tagline:          'Podcast'
baseurl:          /
paginate:         500
collections:
  hackerspublics:
    output:       true
  category:
    output:       true

# Podcast parameters
podcast_title:    Hackers publics
podcast_url:      https://f14e.fr/hackerspublics/
podcast_description:  Avec Hackers publics, partez à la rencontre celles et ceux qui transforment la culture numérique de l’administration. Prenez une grande bouffée d’inspiration et découvrez l’avant-garde de l’innovation publique. Si vous êtes dans l’administration, vous verrez que vous n’êtes pas seul à essayer de changer les choses. Si vous n’en faites pas (encore) partie, vous découvrirez qu’il est possible d’innover tout en ayant un travail qui a du sens ! Et qui sait, ça vous donnera peut-être envie de nous rejoindre pour nous donner un coup de main ?

# Default parameters
defaults:
  -
    scope:
      path: ""
      type: "hackerspublics"
    values:
      layout: episode
      image: https://hackerspublics.fr/public/img/hackerspublics-banner-s2.jpg
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: tag

#SEO tag
title:            Hackers publics
description:      Podcast
url:              https://hackerspublics.fr

author:
  name:           'Hackers publics'
  twitter:        HackersPublics
social:
  name:           Hackers publics
  links:
                  - https://twitter.com/HackersPublics
lang:             fr

plugins:
                  - jekyll-seo-tag
