name: CI-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with nose
      run: nosetests .

  lighthouse-test:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare repo
      uses: actions/checkout@master

    - name: Install npm
      run: npm install

    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheck
      with:
        urls: 'https://f14e.fr/,https://f14e.fr/hackerspublics/,https://f14e.fr/data-policy/,https://f14e.fr/2017/10/02/etat-plateforme-fournisseur-de-services-publics-ouverts/,https://f14e.fr/hackerspublics/ep1_mathilde_bras/'

    - name: Check results
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "100"
        minBestPracticesScore: "100"
        minPerformanceScore: "90"
        minProgressiveWebAppScore: "0"
        minSeoScore: "90"
