name: CI-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with nose
        run: nosetests .

  lighthouse-test:
    runs-on: ubuntu-latest
    container: jekyll/builder:3.8
    services:
      jekyll:
        image: jekyll/builder:3.8
        options: --volume="${{ github.workspace }}:/srv/jekyll"

    steps:
      - name: Prepare repo
        uses: actions/checkout@v2

      - name: Build Jekyll site
        run: jekyll serve --config _config.yml,_config-dev.yml

      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: "http://localhost:4000"
          configPath: 'lighthouserc.json'
