name: CI-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with nose
        run: nosetests .

  lighthouse-test:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun
    # runs-on: ubuntu-latest
    # container:
    #   image: jekyll/builder:3.8
    #   options: -v /__w/seiteta.github.io/seiteta.github.io:/srv/jekyll/:rw
    #
    # steps:
    #   - name: Prepare repo
    #     uses: actions/checkout@v2
    #
    #   # - name: Make directory
    #   #   run: mkdir -vp /__w/seiteta.github.io/seiteta.github.io/_site
    #   #
    #   # - name: Build Jekyll site
    #   #   run: jekyll build --config _config.yml
    #   #
    #   # - name: Print directory
    #   #   run: ls -l /__w/seiteta.github.io/seiteta.github.io/_site
    #
    #   - name:
    #     uses: treosh/lighthouse-ci-action@v3
