name: CI-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare repo
      uses: actions/checkout@v2

    - name: Set up Python [python-test 1/3]
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: Install dependencies [python-test 2/3]
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with nose [python-test 3/3]
      run: nosetests .

    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://f14e.fr/,https://f14e.fr/data-policy/,https://f14e.fr/2017/10/02/etat-plateforme-fournisseur-de-services-publics-ouverts/,https://f14e.fr/hackerspublics/ep1_mathilde_bras/'
