name: CI-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with nose
        run: nosetests .

  jekyll-build-test:
    runs-on: ubuntu-latest
    container:
      image: jekyll/builder:3.8
    steps:
      - name: Prepare repo
        uses: actions/checkout@v2

      - name: Make directory
        run: mkdir -vp /github/_site

      - name: Build Jekyll site
        run: jekyll build --config _config.yml --destination /github/_site

      # - name: Check directory
      #   run: pwd
      #
      # - name: Check directory content
      #   run: ls -l -a
      #
      # - name: Check directory content
      #   run: ls -l -a ~
      #
      # - name: Check directory content
      #   run: ls -l -a /github
      #
      # - name: Check directory content
      #   run: ls -l -a ${{ github.workspace }}


      - name: Upload built site
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: /github/_site

      #
      #
      # - name: Run Lighthouse
      #   uses: foo-software/lighthouse-check-action@master
      #   env:
      #     CHROME_PATH: /usr/bin/google-chrome
      #   with:
      #     urls: 'https://example.com/'
